import {
  AtomIcon,
  BriefcaseIcon,
  CommunityIcon,
  DiamondIcon,
  HomeIcon,
  MiningIcon,
  SwapIcon,
} from './components/icons'
import { assetUrl } from './utils/assets'
import type {
  AdvantageCard,
  CopyText,
  LanguageCode,
  LanguageOption,
  MenuItem,
  ModelItem,
  SubscriptionPlan,
} from './types'

export const brandLogoUrl = assetUrl('/figma/brand-logo.webp')
export const heroBackgroundUrl = assetUrl('/figma/home-hero-bg.webp')
export const heroMainUrl = assetUrl('/figma/hero-card-aus.webp')
export const sectionFrameUrl = assetUrl('/figma/home-section-bg.svg')
export const advantageTitleUrl = assetUrl('/figma/advantage-title.webp')
export const noticeIconUrl = assetUrl('/figma/hero-card-bg.svg')
export const noticeCloseUrl = assetUrl('/figma/hero-card-dots.svg')

export const languageOptions: LanguageOption[] = [
  { code: 'zh-TW', label: '中文（繁體）', flagUrl: assetUrl('/figma/lang-zh-hk.svg') },
  { code: 'en', label: 'English', flagUrl: assetUrl('/figma/lang-en.webp') },
  { code: 'ko', label: '한국어', flagUrl: assetUrl('/figma/lang-ko.svg') },
  { code: 'ja', label: '日本語', flagUrl: assetUrl('/figma/lang-ja.svg') },
  { code: 'th', label: 'ภาษาไทย', flagUrl: assetUrl('/figma/lang-th.svg') },
  { code: 'ms', label: 'Bahasa Melayu', flagUrl: assetUrl('/figma/lang-ms.svg') },
]

export const menuItems: MenuItem[] = [
  { label: '首頁', icon: HomeIcon },
  { label: '認購中心', icon: DiamondIcon },
  { label: '我的社區', icon: CommunityIcon },
  // { label: '我的資產', icon: BriefcaseIcon },
  { label: '算力挖礦', icon: MiningIcon },
  { label: '黃金商城', icon: BriefcaseIcon },
  { label: '待支付訂單', icon: SwapIcon },
  { label: '邀請中心', icon: AtomIcon },
]

export const advantages: AdvantageCard[] = [
  {
    code: '01',
    title: '分級認購與算力',
    description: '限量角色認購、高算力加成、時間復利加成',
    image: assetUrl('/figma/advantage-1.webp'),
  },
  {
    code: '02',
    title: '收益機制',
    description: '靜態挖礦 + 動態級差獎勵 + 全球分紅分潤',
    image: assetUrl('/figma/advantage-2.webp'),
  },
  {
    code: '03',
    title: '通縮模型',
    description: '交易 / 提現 / Swap 稅費自動歸集並觸發回購銷毀',
    image: assetUrl('/figma/advantage-3.webp'),
  },
  {
    code: '04',
    title: '交易體驗',
    description: 'Swap 多終端、鏈上實時交互、無感確認更順滑',
    image: assetUrl('/figma/advantage-4.webp'),
  },
  {
    code: '05',
    title: '架構安全',
    description: '中心化只做撮合與結算，資產留在用戶個人錢包',
    image: assetUrl('/figma/advantage-5.webp'),
  },
]

export const modelItems: ModelItem[] = [
  {
    title: '中心化不碰錢',
    description: '用戶資產（U/AUS',
  },
  {
    title: '鏈上定規則',
    description: 'Swap / 銷毀 / 認購等核心操作必須上鏈，以鏈上結果為準',
  },
  {
    title: '雙向同步',
    description: '鏈上交易完成後同步業務狀態，中心化結算完成後再發起鏈上動作',
  },
]

export const partners = [
  { src: assetUrl('/figma/partner-1.webp'), name: 'DWF Labs' },
  { src: assetUrl('/figma/partner-2.webp'), name: 'PancakeSwap' },
  { src: assetUrl('/figma/partner-3.webp'), name: 'Infinity Ventures Crypto' },
  { src: assetUrl('/figma/partner-4.webp'), name: '7 O\'Clock Capital' },
  { src: assetUrl('/figma/partner-5.webp'), name: 'Mentha Partners' },
  { src: assetUrl('/figma/partner-6.webp'), name: 'SOLRDAO' },
  { src: assetUrl('/figma/partner-7.webp'), name: 'Singchain' },
  { src: assetUrl('/figma/partner-8.webp'), name: 'BINANCE' },
  { src: assetUrl('/figma/partner-9.webp'), name: 'Bitget' },
  { src: assetUrl('/figma/partner-10.webp'), name: 'BingX' },
  { src: assetUrl('/figma/partner-11.webp'), name: 'WEEX' },
  { src: assetUrl('/figma/partner-12.webp'), name: 'Toobit' },
]

export const contacts = [
  { label: 'Telegram', icon: 'telegram' as const },
  { label: 'Twitter', icon: 'twitter' as const },
]

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'ops',
    tabLabel: '運營中心',
    title: '運營中心',
    description: '最高等級節點，全球限量33個，享受5倍算力加成與全球分紅權益',
    amount: '10,000 U',
    quantity: '33 個',
    icon: assetUrl('/figma/subscription-icon-ops.webp'),
    power: '5× · 50,000U',
    level: 'T7',
    reinvest: '-',
    timeBonus: '-',
  },
  {
    id: 'studio',
    tabLabel: '工作室節點',
    title: '工作室節點',
    description: '高級戰略節點，限量100個，4倍算力加成，解鎖T6核心治理權限',
    amount: '5,000 U',
    quantity: '100 個',
    icon: assetUrl('/figma/subscription-icon-super.webp'),
    power: '4× · 20,000U',
    level: 'T6',
    reinvest: '-',
    timeBonus: '-',
  },
  {
    id: 'super',
    tabLabel: '超級節點',
    title: '超級節點',
    description: '核心生態節點，限量1000個，3.5倍算力，支持復投加成與時間復利疊加',
    amount: '1,000 U',
    quantity: '1,000 個',
    icon: assetUrl('/figma/subscription-icon-normal.webp'),
    power: '3.5× · 3,500U',
    level: 'T5',
    reinvest: '2× 每月+10%',
    timeBonus: '月+10% 可疊加',
  },
  {
    id: 'normal',
    tabLabel: '普通節點',
    title: '普通節點',
    description: '生態入門節點，不限數量，3倍算力，支持復投加成與時間復利疊加',
    amount: '500 U',
    quantity: '不限',
    icon: assetUrl('/figma/subscription-icon-gold.webp'),
    power: '3× · 1,500U',
    level: 'T4',
    reinvest: '2× 每月+10%',
    timeBonus: '月+10% 可疊加',
  },
]

export const copyByLanguage: Record<LanguageCode, CopyText> = {
  'zh-TW': {
    home: '首頁',
    subscriptionCenter: '認購中心',
    wallet: '連接錢包',
    walletConnected: '錢包已連接',
    walletMissing: '未檢測到錢包，請安裝 MetaMask 或使用內建錢包瀏覽器',
    walletRejected: '已取消錢包連接',
    walletCopied: '錢包地址已複製',
    walletTitle: '錢包連接',
    walletDescription: '支援 MetaMask 與相容 EVM 的瀏覽器錢包，連接後可顯示地址並進行後續鏈上互動。',
    walletConnectAction: '連接錢包',
    walletCopyAction: '複製地址',
    developing: '該頁面仍在開發中',
    languageTitle: '切換語言',
    close: '關閉',
    notice: '關於BTC提幣手續費調整的通知',
    noticeContent: '尊敬的用戶您好：\n\n為提升鏈上交易效率與資產安全性，平台將於近期對 BTC 提幣手續費進行調整。本次調整基於當前鏈上 Gas 費用波動情況，旨在為用戶提供更穩定的提幣服務。\n\n調整內容：\n• BTC 提幣手續費將由原來的 0.0002 BTC 調整為 0.0003 BTC\n• 調整生效時間：2026年4月1日 00:00（UTC+8）\n• 已提交的提幣請求不受影響\n\n請各位用戶合理安排提幣計畫，如有疑問請聯繫客服團隊。\n\n感謝您的理解與支持！\nAUS 團隊',
    menuClose: '收起選單',
    activeLabel: '當前',
    heroTitle: '去中心化數字黃金\n算力經濟系統',
    heroDescription: '構建一個可以長期存在的鏈上文明',
    heroButton: '認購中心',
    advantagesTitle: 'AUS的優勢',
    advantagesBadge: '算力挖礦 + 通縮銷毀 + 級差社區獎勵',
    modelTitle: 'AUS經濟模型',
    partnersTitle: '合作夥伴',
    contactTitle: 'CONTACT US',
    subscribeNow: '立即認購',
    paymentSuccess: '支付成功',
    walletSwitch: '切換錢包',
    walletDisconnect: '斷開連接',
    walletDisconnected: '錢包已斷開',
    networkCurrent: '當前網絡',
    networkUnsupported: '當前不是 PYTHIA 網絡',
    networkSwitchTitle: '需要切換到 PYTHIA',
    networkSwitchDescription: 'AUS 目前需要在 PYTHIA 公鏈上進行錢包連接與鏈上操作。',
    networkSwitchAction: '切換到 PYTHIA',
    networkReady: '已切換到 PYTHIA 網絡',
    networkTargetName: 'PYTHIA',
    communityTitle: '我的社區',
    communityDesc: '邀請好友加入 AUS 生態，共同成長並獲取社區獎勵',
    inviteTitle: '邀請好友',
    inviteDesc: '分享您的專屬邀請連結，好友完成認購後即可獲得社區獎勵',
    inviteCopy: '複製邀請連結',
    inviteCopied: '邀請連結已複製',
    teamTitle: '我的團隊',
    teamTotal: '團隊總人數',
    teamDirect: '直推',
    teamIndirect: '間推',
    loginRequired: '請先連接錢包',
  },
  en: {
    home: 'Home',
    subscriptionCenter: 'Subscription',
    wallet: 'Connect',
    walletConnected: 'Wallet connected',
    walletMissing: 'No wallet detected. Install MetaMask or open with a wallet browser',
    walletRejected: 'Wallet connection was cancelled',
    walletCopied: 'Wallet address copied',
    walletTitle: 'Wallet',
    walletDescription:
      'Supports MetaMask and compatible EVM wallets. Once connected, the address will be available for on-chain actions.',
    walletConnectAction: 'Connect wallet',
    walletCopyAction: 'Copy address',
    developing: 'This page is still in development',
    languageTitle: 'Language',
    close: 'Close',
    notice: 'BTC withdrawal fee adjustment notice',
    noticeContent: 'Dear Users,\n\nTo improve on-chain transaction efficiency and asset security, the platform will adjust the BTC withdrawal fee in the near future. This adjustment is based on the current on-chain gas fee fluctuations, aiming to provide a more stable withdrawal service.\n\nAdjustment Details:\n• BTC withdrawal fee will be adjusted from 0.0002 BTC to 0.0003 BTC\n• Effective date: April 1, 2026, 00:00 (UTC+8)\n• Pending withdrawal requests will not be affected\n\nPlease plan your withdrawals accordingly. Contact our support team if you have any questions.\n\nThank you for your understanding!\nAUS Team',
    menuClose: 'Hide menu',
    activeLabel: 'Active',
    heroTitle: 'Decentralized Digital Gold\nComputing Power Economy',
    heroDescription: 'Building an on-chain civilization that lasts',
    heroButton: 'Subscription',
    advantagesTitle: 'Why AUS',
    advantagesBadge: 'Mining + Burn + Community Rewards',
    modelTitle: 'AUS Economic Model',
    partnersTitle: 'Partners',
    contactTitle: 'CONTACT US',
    subscribeNow: 'Subscribe now',
    paymentSuccess: 'Payment successful',
    walletSwitch: 'Switch wallet',
    walletDisconnect: 'Disconnect',
    walletDisconnected: 'Wallet disconnected',
    networkCurrent: 'Current network',
    networkUnsupported: 'You are not on PYTHIA',
    networkSwitchTitle: 'Switch to PYTHIA required',
    networkSwitchDescription: 'AUS currently requires the PYTHIA network for wallet connection and on-chain actions.',
    networkSwitchAction: 'Switch to PYTHIA',
    networkReady: 'Switched to PYTHIA',
    networkTargetName: 'PYTHIA',
    communityTitle: 'My Community',
    communityDesc: 'Invite friends to join the AUS ecosystem and earn community rewards',
    inviteTitle: 'Invite Friends',
    inviteDesc: 'Share your exclusive invite link. Earn rewards when friends complete subscriptions',
    inviteCopy: 'Copy invite link',
    inviteCopied: 'Invite link copied',
    teamTitle: 'My Team',
    teamTotal: 'Total Members',
    teamDirect: 'Direct',
    teamIndirect: 'Indirect',
    loginRequired: 'Please connect wallet first',
  },
  ko: {
    home: '홈',
    subscriptionCenter: '구독 센터',
    wallet: '지갑 연결',
    walletConnected: '지갑 연결됨',
    walletMissing: '지갑이 감지되지 않았습니다. MetaMask를 설치하거나 지갑 브라우저를 사용하세요',
    walletRejected: '지갑 연결이 취소되었습니다',
    walletCopied: '지갑 주소가 복사되었습니다',
    walletTitle: '지갑 연결',
    walletDescription: 'MetaMask 및 EVM 호환 브라우저 지갑을 지원합니다. 연결 후 주소가 표시되며 온체인 작업을 진행할 수 있습니다.',
    walletConnectAction: '지갑 연결',
    walletCopyAction: '주소 복사',
    developing: '이 페이지는 개발 중입니다',
    languageTitle: '언어 전환',
    close: '닫기',
    notice: 'BTC 출금 수수료 조정 안내',
    noticeContent: '존경하는 사용자 여러분,\n\n온체인 거래 효율성과 자산 보안을 향상시키기 위해 플랫폼은 BTC 출금 수수료를 조정할 예정입니다.\n\n조정 내용:\n• BTC 출금 수수료: 0.0002 BTC → 0.0003 BTC\n• 적용 시점: 2026년 4월 1일 00:00 (UTC+8)\n• 이미 제출된 출금 요청은 영향 없음\n\n문의 사항이 있으시면 고객 지원팀에 연락해 주세요.\n\n감사합니다!\nAUS 팀',
    menuClose: '메뉴 닫기',
    activeLabel: '현재',
    heroTitle: '탈중앙화 디지털 골드\n컴퓨팅 파워 경제 시스템',
    heroDescription: '장기적으로 존재할 수 있는 온체인 문명을 구축합니다',
    heroButton: '구독 센터',
    advantagesTitle: 'AUS의 장점',
    advantagesBadge: '채굴 + 소각 + 커뮤니티 보상',
    modelTitle: 'AUS 경제 모델',
    partnersTitle: '파트너',
    contactTitle: 'CONTACT US',
    subscribeNow: '지금 구독',
    paymentSuccess: '결제가 완료되었습니다',
    walletSwitch: '지갑 전환',
    walletDisconnect: '연결 해제',
    walletDisconnected: '지갑 연결 해제됨',
    networkCurrent: '현재 네트워크',
    networkUnsupported: '현재 PYTHIA 네트워크가 아닙니다',
    networkSwitchTitle: 'PYTHIA로 전환이 필요합니다',
    networkSwitchDescription: 'AUS는 현재 지갑 연결 및 온체인 작업에 PYTHIA 네트워크가 필요합니다.',
    networkSwitchAction: 'PYTHIA로 전환',
    networkReady: 'PYTHIA로 전환되었습니다',
    networkTargetName: 'PYTHIA',
    communityTitle: '내 커뮤니티',
    communityDesc: '친구를 AUS 생태계에 초대하고 커뮤니티 보상을 받으세요',
    inviteTitle: '친구 초대',
    inviteDesc: '전용 초대 링크를 공유하세요. 친구가 구독을 완료하면 보상을 받을 수 있습니다',
    inviteCopy: '초대 링크 복사',
    inviteCopied: '초대 링크가 복사되었습니다',
    teamTitle: '내 팀',
    teamTotal: '총 인원',
    teamDirect: '직접 추천',
    teamIndirect: '간접 추천',
    loginRequired: '먼저 지갑을 연결해주세요',
  },
  ja: {
    home: 'ホーム',
    subscriptionCenter: 'サブスクリプション',
    wallet: 'ウォレット接続',
    walletConnected: 'ウォレット接続済み',
    walletMissing: 'ウォレットが検出されません。MetaMaskをインストールするか、ウォレットブラウザをご使用ください',
    walletRejected: 'ウォレット接続がキャンセルされました',
    walletCopied: 'ウォレットアドレスがコピーされました',
    walletTitle: 'ウォレット接続',
    walletDescription: 'MetaMaskおよびEVM互換ブラウザウォレットに対応。接続後、アドレスが表示されオンチェーン操作が可能になります。',
    walletConnectAction: 'ウォレット接続',
    walletCopyAction: 'アドレスをコピー',
    developing: 'このページは開発中です',
    languageTitle: '言語切替',
    close: '閉じる',
    notice: 'BTC出金手数料調整のお知らせ',
    noticeContent: 'ユーザーの皆様へ\n\nオンチェーン取引の効率性と資産の安全性を向上させるため、BTC出金手数料を調整いたします。\n\n調整内容：\n• BTC出金手数料：0.0002 BTC → 0.0003 BTC\n• 適用日時：2026年4月1日 00:00（UTC+8）\n• 提出済みの出金リクエストは影響を受けません\n\nご不明な点がございましたら、サポートチームまでお問い合わせください。\n\nご理解いただきありがとうございます！\nAUSチーム',
    menuClose: 'メニューを閉じる',
    activeLabel: '現在',
    heroTitle: '分散型デジタルゴールド\nコンピューティングパワー経済',
    heroDescription: '長期的に存続するオンチェーン文明を構築する',
    heroButton: 'サブスクリプション',
    advantagesTitle: 'AUSの優位性',
    advantagesBadge: 'マイニング + バーン + コミュニティ報酬',
    modelTitle: 'AUS経済モデル',
    partnersTitle: 'パートナー',
    contactTitle: 'CONTACT US',
    subscribeNow: '今すぐ購読',
    paymentSuccess: '支払いに成功しました',
    walletSwitch: 'ウォレット切替',
    walletDisconnect: '切断する',
    walletDisconnected: 'ウォレットが切断されました',
    networkCurrent: '現在のネットワーク',
    networkUnsupported: '現在 PYTHIA ネットワークではありません',
    networkSwitchTitle: 'PYTHIA への切替が必要です',
    networkSwitchDescription: 'AUS のウォレット接続とオンチェーン操作には PYTHIA ネットワークが必要です。',
    networkSwitchAction: 'PYTHIA に切り替える',
    networkReady: 'PYTHIA に切り替わりました',
    networkTargetName: 'PYTHIA',
    communityTitle: 'マイコミュニティ',
    communityDesc: '友人をAUSエコシステムに招待し、コミュニティ報酬を獲得しましょう',
    inviteTitle: '友人を招待',
    inviteDesc: '専用招待リンクを共有。友人が購読を完了すると報酬が得られます',
    inviteCopy: '招待リンクをコピー',
    inviteCopied: '招待リンクがコピーされました',
    teamTitle: 'マイチーム',
    teamTotal: '合計メンバー',
    teamDirect: '直接紹介',
    teamIndirect: '間接紹介',
    loginRequired: 'まずウォレットを接続してください',
  },
  th: {
    home: 'หน้าแรก',
    subscriptionCenter: 'ศูนย์สมัครสมาชิก',
    wallet: 'เชื่อมต่อกระเป๋า',
    walletConnected: 'เชื่อมต่อกระเป๋าแล้ว',
    walletMissing: 'ไม่พบกระเป๋าเงิน กรุณาติดตั้ง MetaMask หรือใช้เบราว์เซอร์กระเป๋าเงิน',
    walletRejected: 'การเชื่อมต่อกระเป๋าถูกยกเลิก',
    walletCopied: 'คัดลอกที่อยู่กระเป๋าแล้ว',
    walletTitle: 'เชื่อมต่อกระเป๋า',
    walletDescription: 'รองรับ MetaMask และกระเป๋าเงินเบราว์เซอร์ที่เข้ากันได้กับ EVM เมื่อเชื่อมต่อแล้ว ที่อยู่จะแสดงสำหรับการดำเนินการบนเชน',
    walletConnectAction: 'เชื่อมต่อกระเป๋า',
    walletCopyAction: 'คัดลอกที่อยู่',
    developing: 'หน้านี้อยู่ระหว่างการพัฒนา',
    languageTitle: 'เปลี่ยนภาษา',
    close: 'ปิด',
    notice: 'ประกาศปรับค่าธรรมเนียมถอน BTC',
    noticeContent: 'เรียนผู้ใช้ทุกท่าน\n\nเพื่อเพิ่มประสิทธิภาพการทำธุรกรรมบนเชนและความปลอดภัยของสินทรัพย์ แพลตฟอร์มจะปรับค่าธรรมเนียมการถอน BTC\n\nรายละเอียดการปรับ:\n• ค่าธรรมเนียมถอน BTC: 0.0002 BTC → 0.0003 BTC\n• มีผล: 1 เมษายน 2026, 00:00 (UTC+8)\n• คำขอถอนที่ส่งแล้วจะไม่ได้รับผลกระทบ\n\nหากมีข้อสงสัย กรุณาติดต่อทีมสนับสนุน\n\nขอบคุณครับ!\nทีม AUS',
    menuClose: 'ซ่อนเมนู',
    activeLabel: 'ปัจจุบัน',
    heroTitle: 'ทองคำดิจิทัลแบบกระจายศูนย์\nระบบเศรษฐกิจพลังประมวลผล',
    heroDescription: 'สร้างอารยธรรมบนเชนที่คงอยู่ได้ยาวนาน',
    heroButton: 'ศูนย์สมัครสมาชิก',
    advantagesTitle: 'ข้อดีของ AUS',
    advantagesBadge: 'ขุด + เผา + รางวัลชุมชน',
    modelTitle: 'โมเดลเศรษฐกิจ AUS',
    partnersTitle: 'พันธมิตร',
    contactTitle: 'CONTACT US',
    subscribeNow: 'สมัครสมาชิกเลย',
    paymentSuccess: 'ชำระเงินสำเร็จ',
    walletSwitch: 'เปลี่ยนกระเป๋า',
    walletDisconnect: 'ตัดการเชื่อมต่อ',
    walletDisconnected: 'ตัดการเชื่อมต่อกระเป๋าแล้ว',
    networkCurrent: 'เครือข่ายปัจจุบัน',
    networkUnsupported: 'ขณะนี้ไม่ได้อยู่บน PYTHIA',
    networkSwitchTitle: 'ต้องสลับไปที่ PYTHIA',
    networkSwitchDescription: 'ขณะนี้ AUS ต้องใช้เครือข่าย PYTHIA สำหรับการเชื่อมต่อกระเป๋าและการทำธุรกรรม on-chain',
    networkSwitchAction: 'สลับไป PYTHIA',
    networkReady: 'สลับไปยัง PYTHIA แล้ว',
    networkTargetName: 'PYTHIA',
    communityTitle: 'ชุมชนของฉัน',
    communityDesc: 'เชิญเพื่อนเข้าร่วมระบบนิเวศ AUS และรับรางวัลชุมชน',
    inviteTitle: 'เชิญเพื่อน',
    inviteDesc: 'แชร์ลิงก์เชิญส่วนตัวของคุณ เพื่อนสมัครสำเร็จรับรางวัลทันที',
    inviteCopy: 'คัดลอกลิงก์เชิญ',
    inviteCopied: 'คัดลอกลิงก์เชิญแล้ว',
    teamTitle: 'ทีมของฉัน',
    teamTotal: 'สมาชิกทั้งหมด',
    teamDirect: 'แนะนำตรง',
    teamIndirect: 'แนะนำอ้อม',
    loginRequired: 'กรุณาเชื่อมต่อกระเป๋าเงินก่อน',
  },
  ms: {
    home: 'Utama',
    subscriptionCenter: 'Pusat Langganan',
    wallet: 'Sambung Dompet',
    walletConnected: 'Dompet disambungkan',
    walletMissing: 'Dompet tidak dikesan. Sila pasang MetaMask atau gunakan pelayar dompet',
    walletRejected: 'Sambungan dompet dibatalkan',
    walletCopied: 'Alamat dompet disalin',
    walletTitle: 'Sambungan Dompet',
    walletDescription: 'Menyokong MetaMask dan dompet pelayar serasi EVM. Selepas disambung, alamat akan dipaparkan untuk operasi on-chain.',
    walletConnectAction: 'Sambung dompet',
    walletCopyAction: 'Salin alamat',
    developing: 'Halaman ini masih dalam pembangunan',
    languageTitle: 'Tukar Bahasa',
    close: 'Tutup',
    notice: 'Notis pelarasan yuran pengeluaran BTC',
    noticeContent: 'Pengguna yang dihormati,\n\nUntuk meningkatkan kecekapan transaksi on-chain dan keselamatan aset, platform akan melaraskan yuran pengeluaran BTC.\n\nButiran pelarasan:\n• Yuran pengeluaran BTC: 0.0002 BTC → 0.0003 BTC\n• Tarikh berkuat kuasa: 1 April 2026, 00:00 (UTC+8)\n• Permintaan pengeluaran yang telah dihantar tidak terjejas\n\nSila hubungi pasukan sokongan jika ada pertanyaan.\n\nTerima kasih!\nPasukan AUS',
    menuClose: 'Sembunyikan menu',
    activeLabel: 'Aktif',
    heroTitle: 'Emas Digital Terdesentralisasi\nSistem Ekonomi Kuasa Pengkomputeran',
    heroDescription: 'Membina tamadun on-chain yang kekal',
    heroButton: 'Pusat Langganan',
    advantagesTitle: 'Kelebihan AUS',
    advantagesBadge: 'Perlombongan + Pembakaran + Ganjaran Komuniti',
    modelTitle: 'Model Ekonomi AUS',
    partnersTitle: 'Rakan Kongsi',
    contactTitle: 'CONTACT US',
    subscribeNow: 'Langgan sekarang',
    paymentSuccess: 'Pembayaran berjaya',
    walletSwitch: 'Tukar dompet',
    walletDisconnect: 'Putuskan sambungan',
    walletDisconnected: 'Dompet diputuskan',
    networkCurrent: 'Rangkaian semasa',
    networkUnsupported: 'Anda kini bukan di PYTHIA',
    networkSwitchTitle: 'Perlu tukar ke PYTHIA',
    networkSwitchDescription: 'AUS kini memerlukan rangkaian PYTHIA untuk sambungan dompet dan tindakan on-chain.',
    networkSwitchAction: 'Tukar ke PYTHIA',
    networkReady: 'Berjaya bertukar ke PYTHIA',
    networkTargetName: 'PYTHIA',
    communityTitle: 'Komuniti Saya',
    communityDesc: 'Jemput rakan menyertai ekosistem AUS dan dapatkan ganjaran komuniti',
    inviteTitle: 'Jemput Rakan',
    inviteDesc: 'Kongsi pautan jemputan eksklusif anda. Dapatkan ganjaran apabila rakan melengkapkan langganan',
    inviteCopy: 'Salin pautan jemputan',
    inviteCopied: 'Pautan jemputan disalin',
    teamTitle: 'Pasukan Saya',
    teamTotal: 'Jumlah Ahli',
    teamDirect: 'Rujukan Langsung',
    teamIndirect: 'Rujukan Tidak Langsung',
    loginRequired: 'Sila sambungkan dompet terlebih dahulu',
  },
}
